version: '2'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - solr
  solr:
    image: solr
    ports:
    - "8983:8983"
    volumes:
    - dropboxFile:/opt/solr/server/solr/dropboxFile
volumes:
  dropboxFile:
    external: true